runtime: python39
entrypoint: gunicorn -b :$PORT --workers=1 main:app

#manual_scaling:
#  instances: 1

automatic_scaling:
  max_instances: 1
  max_concurrent_requests: 1000
  target_throughput_utilization: 0.95
  max_idle_instances: 0
  min_idle_instances: 0

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
